### ISSUE TITLE
Exception Callstack

### ISSUE THREAD

**Issue by developsessions** [IonxSolutions/serilog-sinks-syslog#70]
Is it possible to log the whole exception callstack to syslog? I use the TcpSyslog sink and i use the {Exception} property in the output template.

**Comment by colin-anderson** [comment]
From [the docs](https://github.com/serilog/serilog/wiki/Formatting-Output), the `{Exception}`property is:

> The full exception message and stack trace, formatted across multiple lines. Empty if no exception is associated with the event

Accordingly, if you use a message framing method that supports multi-line text, you should receive the whole stack trace. Of course, your syslog server will need to support such a framing method. Alternatively, if you have to use `LF` delimited messages, you could use something like Graylog to piece multi-line messages back together.

**Comment by Kevin-Andrew** [comment]
@developsessions , @colin-anderson 

Colin answered it perfectly, but to give an example, you could write a quick Unit Test like the following. In `serilog-sinks-syslog\test\Serilog.Sinks.Syslog.Tests\TcpSyslogSinkTests.cs`, I added the following:
```
[Fact]
public async Task Multiline_exception()
{
    // Start a simple TCP syslog server that will capture all received messaged
    var receiver = new TcpSyslogReceiver(null, this.cts.Token);
    receiver.MessageReceived += (_, msg) =>
    {
        SelfLog.WriteLine(msg);
        this.messagesReceived.Add(msg);
        this.countdown.Signal();
    };

    var logger = new LoggerConfiguration();

    logger.WriteTo.TcpSyslog(IPAddress.Loopback.ToString(),
        receiver.IPEndPoint.Port,
        framingType: FramingType.OCTET_COUNTING,
        format: SyslogFormat.RFC5424,
        facility: Facility.Local0,
        outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}")
        .MinimumLevel.Verbose();

    var log = logger.CreateLogger();

    // We will only be sending/testing a single event, but the countdown is expecting 3. Signal it
    // twice now so we don't have to wait for the timeout.
    this.countdown.Signal();
    this.countdown.Signal();

    try
    {
        DivideByZero();

        // We should not get here. A DivideByZeroException should be thrown, handled, and logged below.
    }
    catch (Exception ex)
    {
        var expectedText = new MessageTemplateParser().Parse("Test exception.");

        var le = new LogEvent(DateTimeOffset.UtcNow, LogEventLevel.Fatal, ex, expectedText, Enumerable.Empty<LogEventProperty>());

        log.Write(le);
    }

    log.Dispose();

    // Wait until the server has received all the messages we sent, or the timeout expires
    await this.countdown.WaitAsync(TimeoutInSeconds, this.cts.Token);

    // The server should have received all 3 messages sent by the sink
    this.messagesReceived.Count.ShouldBe(1);
    this.messagesReceived.ShouldAllBe(x => x.Split('\r', '\n').Length > 1);

    this.cts.Cancel();
}

private static int DivideByZero()
{
    // Just an additional method to be called, so as to increase the depth of the stack trace of the exception.
    var i = 0;
    var j = 42;
    var k = j / i;

    return k;
}
```
![image](https://github.com/IonxSolutions/serilog-sinks-syslog/assets/22459191/3030afdf-022e-4993-b163-0cf1506dd386)

And when you run it, it produces the following output:
```
 Serilog.Sinks.Syslog.Tests.TcpSyslogSinkTests.Multiline_exception
   Source: TcpSyslogSinkTests.cs line 150
   Duration: 8.7 sec

  Standard Output: 
2024-03-08T11:58:10.0636691Z <128>1 2024-03-08T11:58:01.544448+00:00 DSGCH0FP72 testhost 13244 - - [11:58:01 FTL] Test exception.
System.DivideByZeroException: Attempted to divide by zero.
   at Serilog.Sinks.Syslog.Tests.TcpSyslogSinkTests.DivideByZero() in C:\VSProjects\serilog-sinks-syslog\test\Serilog.Sinks.Syslog.Tests\TcpSyslogSinkTests.cs:line 210
   at Serilog.Sinks.Syslog.Tests.TcpSyslogSinkTests.<Multiline_exception>d__12.MoveNext() in C:\VSProjects\serilog-sinks-syslog\test\Serilog.Sinks.Syslog.Tests\TcpSyslogSinkTests.cs:line 180
```
![image](https://github.com/IonxSolutions/serilog-sinks-syslog/assets/22459191/7066a597-08f6-47e4-a2ae-f733eb1eb20e)
